# config.yml

backend:
  name: git-gateway
  repo: shinygiggle/shinygiggle.github.io # Path to your Github repository
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
